# ***********************
# The research leading to the development of this program has received funding from the European Union Seventh Framework Programme (FP7/2007-2013) under grant agreement number 309837 (NanoPUZZLES project).
# http://wwww.nanopuzzles.eu
# ************************
#########################################################################################################
# Copyright (c) 2014 Liverpool John Moores University
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or (at
# your option] =  any later version.

# THIS PROGRAM IS MADE AVAILABLE FOR DISTRIBUTION WITHOUT ANY FORM OF WARRANTY TO THE 
# EXTENT PERMITTED BY APPLICABLE LAW.  THE COPYRIGHT HOLDER PROVIDES THE PROGRAM \"AS IS\" 
# WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING, BUT NOT  
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR 
# PURPOSE. THE ENTIRE RISK AS TO THE QUALITY AND PERFORMANCE OF THE PROGRAM LIES
# WITH THE USER.  SHOULD THE PROGRAM PROVE DEFECTIVE IN ANY WAY, THE USER ASSUMES THE
# COST OF ALL NECESSARY SERVICING, REPAIR OR CORRECTION. THE COPYRIGHT HOLDER IS NOT 
# RESPONSIBLE FOR ANY AMENDMENT, MODIFICATION OR OTHER ENHANCEMENT MADE TO THE PROGRAM 
# BY ANY USER WHO REDISTRIBUTES THE PROGRAM SO AMENDED, MODIFIED OR ENHANCED.

# IN NO EVENT UNLESS REQUIRED BY APPLICABLE LAW OR AGREED TO IN WRITING WILL THE 
# COPYRIGHT HOLDER BE LIABLE TO ANY USER FOR DAMAGES, INCLUDING ANY GENERAL, SPECIAL,
# INCIDENTAL OR CONSEQUENTIAL DAMAGES ARISING OUT OF THE USE OR INABILITY TO USE THE
# PROGRAM (INCLUDING BUT NOT LIMITED TO LOSS OF DATA OR DATA BEING RENDERED INACCURATE
# OR LOSSES SUSTAINED BY THE USER OR THIRD PARTIES OR A FAILURE OF THE PROGRAM TO 
# OPERATE WITH ANY OTHER PROGRAMS] = , EVEN IF SUCH HOLDER HAS BEEN ADVISED OF THE 
# POSSIBILITY OF SUCH DAMAGES.

# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#########################################################################################################
from collections import defaultdict

expected_nbi_1_xls_data ={}
expected_nbi_1_xls_data['NBI Material'] = {}
expected_nbi_1_xls_data['NBI Material']['NBI Material Identifier'] = 1.0
expected_nbi_1_xls_data['NBI Material']['Particle Descriptor'] = 'Gold-MEE(1.5 nm)'
expected_nbi_1_xls_data['NBI Material']['Investigator / Material Data Contributor: Name'] = 'Dr. Stacey Harper'
expected_nbi_1_xls_data['NBI Material']['Investigator / Material Data Contributor: Affiliation'] = 'Oregon State University'
expected_nbi_1_xls_data['NBI Material']['Investigator / Material Data Contributor: Email'] = 'stacey.harper@oregonstate.edu'
expected_nbi_1_xls_data['NBI Material']['Material Type'] = 'metal'
expected_nbi_1_xls_data['NBI Material']['Manufacture Date'] = None
expected_nbi_1_xls_data['NBI Material']['Manufacturer'] = 'Jim Hutchison, University of Oregon'
expected_nbi_1_xls_data['NBI Material']['Synthesis Process'] = 'reduction using sodium borohydride in the presence of triphenylphosphine'
expected_nbi_1_xls_data['NBI Material']['Synthesis Precursors'] = 'chloroauric acid (HAuCl4)'
expected_nbi_1_xls_data['NBI Material']['Purity'] = 'ultra pure'
expected_nbi_1_xls_data['NBI Material']['Types of Impurities'] = None
expected_nbi_1_xls_data['NBI Material']['Primary Particle Size: Avg. (nm)'] = 1.5
expected_nbi_1_xls_data['NBI Material']['Primary Particle Size: Min. (nm)'] = None
expected_nbi_1_xls_data['NBI Material']['Primary Particle Size: Max (nm)'] = None
expected_nbi_1_xls_data['NBI Material']['Method of Size Measurement'] = None
expected_nbi_1_xls_data['NBI Material']['Instrument Used for Size Measurement'] = None
expected_nbi_1_xls_data['NBI Material']['Core Shape'] = 'spherical'
expected_nbi_1_xls_data['NBI Material']['Core Structure'] = 'solid'
expected_nbi_1_xls_data['NBI Material']['Crystal Structure'] = None
expected_nbi_1_xls_data['NBI Material']['Core Atomic Composition'] = 'gold [Au]'
expected_nbi_1_xls_data['NBI Material']['Number of Core Atoms'] = 101.0
expected_nbi_1_xls_data['NBI Material']['Mass Core Atoms (ng)'] = 19894.0
expected_nbi_1_xls_data['NBI Material']['Shell Composition'] = None
expected_nbi_1_xls_data['NBI Material']['Shell Surface Shape'] = None
expected_nbi_1_xls_data['NBI Material']['Shell Linkage'] = None
expected_nbi_1_xls_data['NBI Material']['Outermost Surface Functional Groups'] = '2-(2-mercaptoethoxy)ethanol [MEE]'
expected_nbi_1_xls_data['NBI Material']['Surface Chemistry Linkage Group / Type'] = None
expected_nbi_1_xls_data['NBI Material']['Density of Surface Covered with Ligands (%)'] =  None
expected_nbi_1_xls_data['NBI Material']['Minimum Number of Ligands'] = 30.0
expected_nbi_1_xls_data['NBI Material']['Maximum Nunber of Ligands'] = 35.0
expected_nbi_1_xls_data['NBI Material']['Mass of Core + Shell + Linkages and Ligands (ng)'] = None
expected_nbi_1_xls_data['NBI Material']['Surface Area (Core + Shell + Ligands) (mm2)'] = None
expected_nbi_1_xls_data['NBI Material']['Method Used to Determine Surface Area'] = None
expected_nbi_1_xls_data['NBI Material']['Surface Charge: (positive, negative, neutral)'] = 'neutral'
expected_nbi_1_xls_data['NBI Material']['Surface Charge: Value'] = None
expected_nbi_1_xls_data['NBI Material']['Surface Charge: Method'] = None
expected_nbi_1_xls_data['NBI Material']['Redox Potential (volts)'] = None
expected_nbi_1_xls_data['NBI Material']['Solubility / Dispersity Medium'] = None
expected_nbi_1_xls_data['NBI Material']['Maximum Solubility Amount (ppm)'] = None
expected_nbi_1_xls_data['NBI Material']['Solubility Reference Temperature (Celsius)'] = None
expected_nbi_1_xls_data['NBI Material']['Hydrophilic'] = None
expected_nbi_1_xls_data['NBI Material']['Lipophilic'] = None
expected_nbi_1_xls_data['NBI Material']['Stability of Dispersions'] = None
expected_nbi_1_xls_data['NBI Material']['Publication Authors'] = None
expected_nbi_1_xls_data['NBI Material']['Publication Year'] = None
expected_nbi_1_xls_data['NBI Material']['Publication Journal'] = None
expected_nbi_1_xls_data['NBI Material']['Publication Title'] = None
expected_nbi_1_xls_data['NBI Material']['Publication DOI'] = None
expected_nbi_1_xls_data['NBI-EMZ Exp. Design'] = {}
expected_nbi_1_xls_data['NBI-EMZ Exp. Design']['NBI Experiment ID'] = 1.0
expected_nbi_1_xls_data['NBI-EMZ Exp. Design']['NBI Material Identifier'] = 1.0
expected_nbi_1_xls_data['NBI-EMZ Exp. Design']['Exposure Metric / Assay'] = None 
expected_nbi_1_xls_data['NBI-EMZ Exp. Design']['Primary Exposure Route'] = 'dermal'
expected_nbi_1_xls_data['NBI-EMZ Exp. Design']['Primary Exposure Delivery'] = 'waterborne'
expected_nbi_1_xls_data['NBI-EMZ Exp. Design']['Secondary Exposure Route'] = 'oral'
expected_nbi_1_xls_data['NBI-EMZ Exp. Design']['Secondary Exposure Delivery'] = 'waterborne'
expected_nbi_1_xls_data['NBI-EMZ Exp. Design']['Tertiary Exposure Route'] = None
expected_nbi_1_xls_data['NBI-EMZ Exp. Design']['Tertiary Exposure Delivery'] = None
expected_nbi_1_xls_data['NBI-EMZ Exp. Design']['Study Factor(s)'] = None
expected_nbi_1_xls_data['NBI-EMZ Exp. Design']['Exposure Organism'] = 'zebrafish'
expected_nbi_1_xls_data['NBI-EMZ Exp. Design']['Exposure Organism Life stage'] = 'embryo'
expected_nbi_1_xls_data['NBI-EMZ Exp. Design']['Exposure Length Classification'] = None
expected_nbi_1_xls_data['NBI-EMZ Exp. Design']['Duration of Exposure (hours)'] = 112.0
expected_nbi_1_xls_data['NBI-EMZ Exp. Design']['Investigation Title'] = None
expected_nbi_1_xls_data['NBI-EMZ Exp. Design']['Investigation Description'] = None
expected_nbi_1_xls_data['NBI-EMZ Exp. Design']['Investigator Name'] = None
expected_nbi_1_xls_data['NBI-EMZ Exp. Design']['Investigator Affiliation'] = None
expected_nbi_1_xls_data['NBI-EMZ Exp. Design']['Investigator Email'] = None
expected_nbi_1_xls_data['NBI-EMZ Exp. Design']['Study Start Date'] = None
expected_nbi_1_xls_data['NBI-EMZ Exp. Design']['Exposure Organism Gender'] = 'mixed'
expected_nbi_1_xls_data['NBI-EMZ Exp. Design']['Exposure Organism Average Weight (mg)'] = '1 mg' #<TO DO>:MAKE THIS NUMERIC IN NBIrecordParser.py THEN UPDATE EXPECTED VALUE HERE
expected_nbi_1_xls_data['NBI-EMZ Exp. Design']['Exposure Organism Initial Age (hours post-fertilization at start of exposure)'] = 8
expected_nbi_1_xls_data['NBI-EMZ Exp. Design']['Continuity of Exposure'] = 'Continuous'
expected_nbi_1_xls_data['NBI-EMZ Exp. Design']['Exposure Temperature (Celsius)'] = None
expected_nbi_1_xls_data['NBI-EMZ Exp. Design']['Exposure Media'] = 'fish water'
expected_nbi_1_xls_data['NBI-EMZ Exp. Design']['Media Composition'] = None
expected_nbi_1_xls_data['NBI-EMZ Exp. Design']['Media pH'] = None
expected_nbi_1_xls_data['NBI-EMZ Exp. Design']['Material Zeta Potential in Media (mV)'] = None 
expected_nbi_1_xls_data['NBI-EMZ Exp. Design']['Stable Average Agglomerate Size in Media (nm)'] = None
expected_nbi_1_xls_data['NBI-EMZ Exp. Design']['Stable Agglomerate Size in Media Minimum (nm)'] = None
expected_nbi_1_xls_data['NBI-EMZ Exp. Design']['Stable Agglomerate Size in Media Maximum (nm)'] = None
expected_nbi_1_xls_data['NBI-EMZ Exp. Design']['Nanomaterial Preparation'] = None
expected_nbi_1_xls_data['NBI-EMZ Exp. Design']['Experimental Notes'] = None
expected_nbi_1_xls_data['NBI-EMZ Exp. Design']['LC50 (ppm)'] = None
expected_nbi_1_xls_data['NBI-EMZ Exp. Design']['NOAEL (ppm)'] = None
expected_nbi_1_xls_data['NBI-EMZ Exp. Design']['Weighted EZ Metric EC50 (ppm)'] = None 
expected_nbi_1_xls_data['NBI-EMZ Exp. Design']['Additive EZ Metric EC50 (ppm)'] = None
expected_nbi_1_xls_data['NBI-EMZ Exp. Design']['Publication Authors'] = None
expected_nbi_1_xls_data['NBI-EMZ Exp. Design']['Publication Year'] = None
expected_nbi_1_xls_data['NBI-EMZ Exp. Design']['Publication Journal'] = None
expected_nbi_1_xls_data['NBI-EMZ Exp. Design']['Publication Title'] = None
expected_nbi_1_xls_data['NBI-EMZ Exp. Design']['Publication DOI'] = None
expected_nbi_1_xls_data['NBI-EMZ Data'] = defaultdict(dict)
expected_nbi_1_xls_data['NBI-EMZ Data'][9]['Dosage Concentrations Used (ppm)'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][9]['Weighted EZ Metric Score'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][9]['Additive EZ Metric Score'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][9]['24 hpf evaluation_M_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][9]['24 hpf evaluation_M_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][9]['24 hpf evaluation_DP_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][9]['24 hpf evaluation_DP_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][9]['24 hpf evaluation_SM_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][9]['24 hpf evaluation_SM_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][9]['24 hpf evaluation_N_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][9]['24 hpf evaluation_N_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][9]['120 hpf evaluation_M_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][9]['120 hpf evaluation_M_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][9]['120 hpf evaluation_Y_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][9]['120 hpf evaluation_Y_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][9]['120 hpf evaluation_A_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][9]['120 hpf evaluation_A_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][9]['120 hpf evaluation_E_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][9]['120 hpf evaluation_E_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][9]['120 hpf evaluation_Sn_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][9]['120 hpf evaluation_Sn_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][9]['120 hpf evaluation_J_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][9]['120 hpf evaluation_J_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][9]['120 hpf evaluation_O_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][9]['120 hpf evaluation_O_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][9]['120 hpf evaluation_H_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][9]['120 hpf evaluation_H_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][9]['120 hpf evaluation_B_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][9]['120 hpf evaluation_B_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][9]['120 hpf evaluation_So_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][9]['120 hpf evaluation_So_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][9]['120 hpf evaluation_PF_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][9]['120 hpf evaluation_PF_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][9]['120 hpf evaluation_CF_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][9]['120 hpf evaluation_CF_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][9]['120 hpf evaluation_P_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][9]['120 hpf evaluation_P_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][9]['120 hpf evaluation_C_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][9]['120 hpf evaluation_C_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][9]['120 hpf evaluation_T_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][9]['120 hpf evaluation_T_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][9]['120 hpf evaluation_SB_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][9]['120 hpf evaluation_SB_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][9]['120 hpf evaluation_TR_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][9]['120 hpf evaluation_TR_no'] = 24.0
#
expected_nbi_1_xls_data['NBI-EMZ Data'][10]['Dosage Concentrations Used (ppm)'] = 0.016
expected_nbi_1_xls_data['NBI-EMZ Data'][10]['Weighted EZ Metric Score'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][10]['Additive EZ Metric Score'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][10]['24 hpf evaluation_M_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][10]['24 hpf evaluation_M_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][10]['24 hpf evaluation_DP_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][10]['24 hpf evaluation_DP_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][10]['24 hpf evaluation_SM_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][10]['24 hpf evaluation_SM_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][10]['24 hpf evaluation_N_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][10]['24 hpf evaluation_N_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][10]['120 hpf evaluation_M_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][10]['120 hpf evaluation_M_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][10]['120 hpf evaluation_Y_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][10]['120 hpf evaluation_Y_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][10]['120 hpf evaluation_A_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][10]['120 hpf evaluation_A_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][10]['120 hpf evaluation_E_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][10]['120 hpf evaluation_E_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][10]['120 hpf evaluation_Sn_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][10]['120 hpf evaluation_Sn_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][10]['120 hpf evaluation_J_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][10]['120 hpf evaluation_J_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][10]['120 hpf evaluation_O_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][10]['120 hpf evaluation_O_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][10]['120 hpf evaluation_H_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][10]['120 hpf evaluation_H_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][10]['120 hpf evaluation_B_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][10]['120 hpf evaluation_B_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][10]['120 hpf evaluation_So_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][10]['120 hpf evaluation_So_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][10]['120 hpf evaluation_PF_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][10]['120 hpf evaluation_PF_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][10]['120 hpf evaluation_CF_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][10]['120 hpf evaluation_CF_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][10]['120 hpf evaluation_P_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][10]['120 hpf evaluation_P_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][10]['120 hpf evaluation_C_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][10]['120 hpf evaluation_C_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][10]['120 hpf evaluation_T_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][10]['120 hpf evaluation_T_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][10]['120 hpf evaluation_SB_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][10]['120 hpf evaluation_SB_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][10]['120 hpf evaluation_TR_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][10]['120 hpf evaluation_TR_no'] = 24.0
#
expected_nbi_1_xls_data['NBI-EMZ Data'][11]['Dosage Concentrations Used (ppm)'] = 0.08
expected_nbi_1_xls_data['NBI-EMZ Data'][11]['Weighted EZ Metric Score'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][11]['Additive EZ Metric Score'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][11]['24 hpf evaluation_M_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][11]['24 hpf evaluation_M_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][11]['24 hpf evaluation_DP_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][11]['24 hpf evaluation_DP_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][11]['24 hpf evaluation_SM_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][11]['24 hpf evaluation_SM_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][11]['24 hpf evaluation_N_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][11]['24 hpf evaluation_N_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][11]['120 hpf evaluation_M_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][11]['120 hpf evaluation_M_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][11]['120 hpf evaluation_Y_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][11]['120 hpf evaluation_Y_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][11]['120 hpf evaluation_A_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][11]['120 hpf evaluation_A_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][11]['120 hpf evaluation_E_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][11]['120 hpf evaluation_E_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][11]['120 hpf evaluation_Sn_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][11]['120 hpf evaluation_Sn_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][11]['120 hpf evaluation_J_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][11]['120 hpf evaluation_J_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][11]['120 hpf evaluation_O_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][11]['120 hpf evaluation_O_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][11]['120 hpf evaluation_H_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][11]['120 hpf evaluation_H_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][11]['120 hpf evaluation_B_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][11]['120 hpf evaluation_B_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][11]['120 hpf evaluation_So_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][11]['120 hpf evaluation_So_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][11]['120 hpf evaluation_PF_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][11]['120 hpf evaluation_PF_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][11]['120 hpf evaluation_CF_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][11]['120 hpf evaluation_CF_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][11]['120 hpf evaluation_P_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][11]['120 hpf evaluation_P_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][11]['120 hpf evaluation_C_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][11]['120 hpf evaluation_C_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][11]['120 hpf evaluation_T_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][11]['120 hpf evaluation_T_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][11]['120 hpf evaluation_SB_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][11]['120 hpf evaluation_SB_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][11]['120 hpf evaluation_TR_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][11]['120 hpf evaluation_TR_no'] = 24.0
#
expected_nbi_1_xls_data['NBI-EMZ Data'][12]['Dosage Concentrations Used (ppm)'] = 0.4
expected_nbi_1_xls_data['NBI-EMZ Data'][12]['Weighted EZ Metric Score'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][12]['Additive EZ Metric Score'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][12]['24 hpf evaluation_M_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][12]['24 hpf evaluation_M_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][12]['24 hpf evaluation_DP_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][12]['24 hpf evaluation_DP_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][12]['24 hpf evaluation_SM_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][12]['24 hpf evaluation_SM_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][12]['24 hpf evaluation_N_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][12]['24 hpf evaluation_N_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][12]['120 hpf evaluation_M_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][12]['120 hpf evaluation_M_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][12]['120 hpf evaluation_Y_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][12]['120 hpf evaluation_Y_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][12]['120 hpf evaluation_A_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][12]['120 hpf evaluation_A_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][12]['120 hpf evaluation_E_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][12]['120 hpf evaluation_E_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][12]['120 hpf evaluation_Sn_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][12]['120 hpf evaluation_Sn_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][12]['120 hpf evaluation_J_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][12]['120 hpf evaluation_J_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][12]['120 hpf evaluation_O_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][12]['120 hpf evaluation_O_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][12]['120 hpf evaluation_H_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][12]['120 hpf evaluation_H_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][12]['120 hpf evaluation_B_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][12]['120 hpf evaluation_B_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][12]['120 hpf evaluation_So_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][12]['120 hpf evaluation_So_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][12]['120 hpf evaluation_PF_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][12]['120 hpf evaluation_PF_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][12]['120 hpf evaluation_CF_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][12]['120 hpf evaluation_CF_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][12]['120 hpf evaluation_P_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][12]['120 hpf evaluation_P_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][12]['120 hpf evaluation_C_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][12]['120 hpf evaluation_C_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][12]['120 hpf evaluation_T_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][12]['120 hpf evaluation_T_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][12]['120 hpf evaluation_SB_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][12]['120 hpf evaluation_SB_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][12]['120 hpf evaluation_TR_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][12]['120 hpf evaluation_TR_no'] = 24.0
#
expected_nbi_1_xls_data['NBI-EMZ Data'][13]['Dosage Concentrations Used (ppm)'] = 2
expected_nbi_1_xls_data['NBI-EMZ Data'][13]['Weighted EZ Metric Score'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][13]['Additive EZ Metric Score'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][13]['24 hpf evaluation_M_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][13]['24 hpf evaluation_M_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][13]['24 hpf evaluation_DP_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][13]['24 hpf evaluation_DP_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][13]['24 hpf evaluation_SM_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][13]['24 hpf evaluation_SM_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][13]['24 hpf evaluation_N_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][13]['24 hpf evaluation_N_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][13]['120 hpf evaluation_M_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][13]['120 hpf evaluation_M_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][13]['120 hpf evaluation_Y_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][13]['120 hpf evaluation_Y_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][13]['120 hpf evaluation_A_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][13]['120 hpf evaluation_A_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][13]['120 hpf evaluation_E_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][13]['120 hpf evaluation_E_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][13]['120 hpf evaluation_Sn_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][13]['120 hpf evaluation_Sn_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][13]['120 hpf evaluation_J_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][13]['120 hpf evaluation_J_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][13]['120 hpf evaluation_O_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][13]['120 hpf evaluation_O_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][13]['120 hpf evaluation_H_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][13]['120 hpf evaluation_H_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][13]['120 hpf evaluation_B_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][13]['120 hpf evaluation_B_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][13]['120 hpf evaluation_So_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][13]['120 hpf evaluation_So_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][13]['120 hpf evaluation_PF_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][13]['120 hpf evaluation_PF_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][13]['120 hpf evaluation_CF_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][13]['120 hpf evaluation_CF_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][13]['120 hpf evaluation_P_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][13]['120 hpf evaluation_P_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][13]['120 hpf evaluation_C_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][13]['120 hpf evaluation_C_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][13]['120 hpf evaluation_T_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][13]['120 hpf evaluation_T_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][13]['120 hpf evaluation_SB_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][13]['120 hpf evaluation_SB_no'] = 24.0
expected_nbi_1_xls_data['NBI-EMZ Data'][13]['120 hpf evaluation_TR_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][13]['120 hpf evaluation_TR_no'] = 24.0
#
expected_nbi_1_xls_data['NBI-EMZ Data'][14]['Dosage Concentrations Used (ppm)'] = 10
expected_nbi_1_xls_data['NBI-EMZ Data'][14]['Weighted EZ Metric Score'] = 0.0475
expected_nbi_1_xls_data['NBI-EMZ Data'][14]['Additive EZ Metric Score'] = 0.125
expected_nbi_1_xls_data['NBI-EMZ Data'][14]['24 hpf evaluation_M_yes'] = 1.0
expected_nbi_1_xls_data['NBI-EMZ Data'][14]['24 hpf evaluation_M_no'] = 23.0
expected_nbi_1_xls_data['NBI-EMZ Data'][14]['24 hpf evaluation_DP_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][14]['24 hpf evaluation_DP_no'] = 23.0
expected_nbi_1_xls_data['NBI-EMZ Data'][14]['24 hpf evaluation_SM_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][14]['24 hpf evaluation_SM_no'] = 23.0
expected_nbi_1_xls_data['NBI-EMZ Data'][14]['24 hpf evaluation_N_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][14]['24 hpf evaluation_N_no'] = 23.0
expected_nbi_1_xls_data['NBI-EMZ Data'][14]['120 hpf evaluation_M_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][14]['120 hpf evaluation_M_no'] = 23.0
expected_nbi_1_xls_data['NBI-EMZ Data'][14]['120 hpf evaluation_Y_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][14]['120 hpf evaluation_Y_no'] = 23.0
expected_nbi_1_xls_data['NBI-EMZ Data'][14]['120 hpf evaluation_A_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][14]['120 hpf evaluation_A_no'] = 23.0
expected_nbi_1_xls_data['NBI-EMZ Data'][14]['120 hpf evaluation_E_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][14]['120 hpf evaluation_E_no'] = 23.0
expected_nbi_1_xls_data['NBI-EMZ Data'][14]['120 hpf evaluation_Sn_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][14]['120 hpf evaluation_Sn_no'] = 23.0
expected_nbi_1_xls_data['NBI-EMZ Data'][14]['120 hpf evaluation_J_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][14]['120 hpf evaluation_J_no'] = 23.0
expected_nbi_1_xls_data['NBI-EMZ Data'][14]['120 hpf evaluation_O_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][14]['120 hpf evaluation_O_no'] = 23.0
expected_nbi_1_xls_data['NBI-EMZ Data'][14]['120 hpf evaluation_H_yes'] = 1.0
expected_nbi_1_xls_data['NBI-EMZ Data'][14]['120 hpf evaluation_H_no'] = 22.0
expected_nbi_1_xls_data['NBI-EMZ Data'][14]['120 hpf evaluation_B_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][14]['120 hpf evaluation_B_no'] = 23.0
expected_nbi_1_xls_data['NBI-EMZ Data'][14]['120 hpf evaluation_So_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][14]['120 hpf evaluation_So_no'] = 23.0
expected_nbi_1_xls_data['NBI-EMZ Data'][14]['120 hpf evaluation_PF_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][14]['120 hpf evaluation_PF_no'] = 23.0
expected_nbi_1_xls_data['NBI-EMZ Data'][14]['120 hpf evaluation_CF_yes'] = 1.0
expected_nbi_1_xls_data['NBI-EMZ Data'][14]['120 hpf evaluation_CF_no'] = 22.0
expected_nbi_1_xls_data['NBI-EMZ Data'][14]['120 hpf evaluation_P_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][14]['120 hpf evaluation_P_no'] = 23.0
expected_nbi_1_xls_data['NBI-EMZ Data'][14]['120 hpf evaluation_C_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][14]['120 hpf evaluation_C_no'] = 23.0
expected_nbi_1_xls_data['NBI-EMZ Data'][14]['120 hpf evaluation_T_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][14]['120 hpf evaluation_T_no'] = 23.0
expected_nbi_1_xls_data['NBI-EMZ Data'][14]['120 hpf evaluation_SB_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][14]['120 hpf evaluation_SB_no'] = 23.0
expected_nbi_1_xls_data['NBI-EMZ Data'][14]['120 hpf evaluation_TR_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][14]['120 hpf evaluation_TR_no'] = 23.0
#
expected_nbi_1_xls_data['NBI-EMZ Data'][15]['Dosage Concentrations Used (ppm)'] = 50
expected_nbi_1_xls_data['NBI-EMZ Data'][15]['Weighted EZ Metric Score'] = 0.09125
expected_nbi_1_xls_data['NBI-EMZ Data'][15]['Additive EZ Metric Score'] = 0.25
expected_nbi_1_xls_data['NBI-EMZ Data'][15]['24 hpf evaluation_M_yes'] = 1.0
expected_nbi_1_xls_data['NBI-EMZ Data'][15]['24 hpf evaluation_M_no'] = 23.0
expected_nbi_1_xls_data['NBI-EMZ Data'][15]['24 hpf evaluation_DP_yes'] = 1.0
expected_nbi_1_xls_data['NBI-EMZ Data'][15]['24 hpf evaluation_DP_no'] = 22.0
expected_nbi_1_xls_data['NBI-EMZ Data'][15]['24 hpf evaluation_SM_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][15]['24 hpf evaluation_SM_no'] = 23.0
expected_nbi_1_xls_data['NBI-EMZ Data'][15]['24 hpf evaluation_N_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][15]['24 hpf evaluation_N_no'] = 22.0
expected_nbi_1_xls_data['NBI-EMZ Data'][15]['120 hpf evaluation_M_yes'] = 1.0
expected_nbi_1_xls_data['NBI-EMZ Data'][15]['120 hpf evaluation_M_no'] = 22.0
expected_nbi_1_xls_data['NBI-EMZ Data'][15]['120 hpf evaluation_Y_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][15]['120 hpf evaluation_Y_no'] = 22.0
expected_nbi_1_xls_data['NBI-EMZ Data'][15]['120 hpf evaluation_A_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][15]['120 hpf evaluation_A_no'] = 22.0
expected_nbi_1_xls_data['NBI-EMZ Data'][15]['120 hpf evaluation_E_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][15]['120 hpf evaluation_E_no'] = 22.0
expected_nbi_1_xls_data['NBI-EMZ Data'][15]['120 hpf evaluation_Sn_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][15]['120 hpf evaluation_Sn_no'] = 22.0
expected_nbi_1_xls_data['NBI-EMZ Data'][15]['120 hpf evaluation_J_yes'] = 1.0
expected_nbi_1_xls_data['NBI-EMZ Data'][15]['120 hpf evaluation_J_no'] = 21.0
expected_nbi_1_xls_data['NBI-EMZ Data'][15]['120 hpf evaluation_O_yes'] = 1.0
expected_nbi_1_xls_data['NBI-EMZ Data'][15]['120 hpf evaluation_O_no'] = 21.0
expected_nbi_1_xls_data['NBI-EMZ Data'][15]['120 hpf evaluation_H_yes'] = 1.0
expected_nbi_1_xls_data['NBI-EMZ Data'][15]['120 hpf evaluation_H_no'] = 21.0
expected_nbi_1_xls_data['NBI-EMZ Data'][15]['120 hpf evaluation_B_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][15]['120 hpf evaluation_B_no'] = 22.0
expected_nbi_1_xls_data['NBI-EMZ Data'][15]['120 hpf evaluation_So_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][15]['120 hpf evaluation_So_no'] = 22.0
expected_nbi_1_xls_data['NBI-EMZ Data'][15]['120 hpf evaluation_PF_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][15]['120 hpf evaluation_PF_no'] = 22.0
expected_nbi_1_xls_data['NBI-EMZ Data'][15]['120 hpf evaluation_CF_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][15]['120 hpf evaluation_CF_no'] = 22.0
expected_nbi_1_xls_data['NBI-EMZ Data'][15]['120 hpf evaluation_P_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][15]['120 hpf evaluation_P_no'] = 22.0
expected_nbi_1_xls_data['NBI-EMZ Data'][15]['120 hpf evaluation_C_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][15]['120 hpf evaluation_C_no'] = 22.0
expected_nbi_1_xls_data['NBI-EMZ Data'][15]['120 hpf evaluation_T_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][15]['120 hpf evaluation_T_no'] = 22.0
expected_nbi_1_xls_data['NBI-EMZ Data'][15]['120 hpf evaluation_SB_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][15]['120 hpf evaluation_SB_no'] = 22.0
expected_nbi_1_xls_data['NBI-EMZ Data'][15]['120 hpf evaluation_TR_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][15]['120 hpf evaluation_TR_no'] = 22.0
#
expected_nbi_1_xls_data['NBI-EMZ Data'][16]['Dosage Concentrations Used (ppm)'] = 250
expected_nbi_1_xls_data['NBI-EMZ Data'][16]['Weighted EZ Metric Score'] = 0.089583333333 #truncated from copied value to 12 dp ... to ensure matches Python extracted value...
expected_nbi_1_xls_data['NBI-EMZ Data'][16]['Additive EZ Metric Score'] = 0.208333333333 #truncated from copied value to 12 dp ... to ensure matches Python extracted value...
expected_nbi_1_xls_data['NBI-EMZ Data'][16]['24 hpf evaluation_M_yes'] = 1.0
expected_nbi_1_xls_data['NBI-EMZ Data'][16]['24 hpf evaluation_M_no'] = 23.0
expected_nbi_1_xls_data['NBI-EMZ Data'][16]['24 hpf evaluation_DP_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][16]['24 hpf evaluation_DP_no'] = 23.0
expected_nbi_1_xls_data['NBI-EMZ Data'][16]['24 hpf evaluation_SM_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][16]['24 hpf evaluation_SM_no'] = 23.0
expected_nbi_1_xls_data['NBI-EMZ Data'][16]['24 hpf evaluation_N_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][16]['24 hpf evaluation_N_no'] = 22.0
expected_nbi_1_xls_data['NBI-EMZ Data'][16]['120 hpf evaluation_M_yes'] = 1.0
expected_nbi_1_xls_data['NBI-EMZ Data'][16]['120 hpf evaluation_M_no'] = 22.0
expected_nbi_1_xls_data['NBI-EMZ Data'][16]['120 hpf evaluation_Y_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][16]['120 hpf evaluation_Y_no'] = 22.0
expected_nbi_1_xls_data['NBI-EMZ Data'][16]['120 hpf evaluation_A_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][16]['120 hpf evaluation_A_no'] = 22.0
expected_nbi_1_xls_data['NBI-EMZ Data'][16]['120 hpf evaluation_E_yes'] = 1.0
expected_nbi_1_xls_data['NBI-EMZ Data'][16]['120 hpf evaluation_E_no'] = 21.0
expected_nbi_1_xls_data['NBI-EMZ Data'][16]['120 hpf evaluation_Sn_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][16]['120 hpf evaluation_Sn_no'] = 22.0
expected_nbi_1_xls_data['NBI-EMZ Data'][16]['120 hpf evaluation_J_yes'] = 1.0
expected_nbi_1_xls_data['NBI-EMZ Data'][16]['120 hpf evaluation_J_no'] = 21.0
expected_nbi_1_xls_data['NBI-EMZ Data'][16]['120 hpf evaluation_O_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][16]['120 hpf evaluation_O_no'] = 22.0
expected_nbi_1_xls_data['NBI-EMZ Data'][16]['120 hpf evaluation_H_yes'] = 1.0
expected_nbi_1_xls_data['NBI-EMZ Data'][16]['120 hpf evaluation_H_no'] = 21.0
expected_nbi_1_xls_data['NBI-EMZ Data'][16]['120 hpf evaluation_B_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][16]['120 hpf evaluation_B_no'] = 22.0
expected_nbi_1_xls_data['NBI-EMZ Data'][16]['120 hpf evaluation_So_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][16]['120 hpf evaluation_So_no'] = 22.0
expected_nbi_1_xls_data['NBI-EMZ Data'][16]['120 hpf evaluation_PF_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][16]['120 hpf evaluation_PF_no'] = 22.0
expected_nbi_1_xls_data['NBI-EMZ Data'][16]['120 hpf evaluation_CF_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][16]['120 hpf evaluation_CF_no'] = 22.0
expected_nbi_1_xls_data['NBI-EMZ Data'][16]['120 hpf evaluation_P_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][16]['120 hpf evaluation_P_no'] = 22.0
expected_nbi_1_xls_data['NBI-EMZ Data'][16]['120 hpf evaluation_C_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][16]['120 hpf evaluation_C_no'] = 22.0
expected_nbi_1_xls_data['NBI-EMZ Data'][16]['120 hpf evaluation_T_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][16]['120 hpf evaluation_T_no'] = 22.0
expected_nbi_1_xls_data['NBI-EMZ Data'][16]['120 hpf evaluation_SB_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][16]['120 hpf evaluation_SB_no'] = 22.0
expected_nbi_1_xls_data['NBI-EMZ Data'][16]['120 hpf evaluation_TR_yes'] = 0.0
expected_nbi_1_xls_data['NBI-EMZ Data'][16]['120 hpf evaluation_TR_no'] = 22.0
